// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  userGuideSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
  ],
  adminGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'admin-guide',
    },
  ],
};

export default sidebars;
